In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv('creditcard.csv') 
data

Time        V1        V2        V3        V4        V5        V6  \
0          0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388   
1          0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361   
2          1 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499   
3          1 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203   
4          2 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921   
...      ...       ...       ...       ...       ...       ...       ...   
39994  40049 -2.856643 -1.580895  1.183275 -1.862689 -2.579951 -1.043656   
39995  40049 -1.051131  0.606656  0.441297  0.590587 -0.118730  1.010767   
39996  40049  1.188332  0.360587 -0.024267  1.179898 -0.095200 -0.975171   
39997  40050  1.038810 -2.090833  0.852849 -0.847290 -2.112321  0.291188   
39998  40052  1.211027  0.614544 -0.459212  0.900736  0.135725 -1.175774   

             V7        V8        V9  ...       V21       V22       V23  \
0      0.239599  0.098698  0.363787  ... -0.018307  0.277838 -0.110474   
1     -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288   
2      0.791461  0.247676 -1.514654  ...  0.247998  0.771679  0.909412   
3      0.237609  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321   
4      0.592941 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458   
...         ...       ...       ...  ...       ...       ...       ...   
39994 -1.007610  0.919906 -1.879716  ... -0.012102 -0.304192 -0.142939   
39995  2.282192 -0.751310  0.141134  ... -0.168207  0.495169 -0.066540   
39996  0.403633 -0.160097 -0.460291  ...  0.063470  0.115945 -0.129453   
39997 -1.321491  0.007713 -0.771225  ... -0.059743  0.138289 -0.341212   
39998  0.337603 -0.198540 -0.188104  ... -0.105254 -0.214124 -0.013156   

            V24       V25       V26       V27       V28  Amount  Class  
0      0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62      0  
1     -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69      0  
2     -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66      0  
3     -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50      0  
4      0.141267 -0.206010  0.502292  0.219422  0.215153   69.99      0  
...         ...       ...       ...       ...       ...     ...    ...  
39994  0.659917  0.200746 -0.314130  0.273768 -0.199219  215.09      0  
39995 -0.904026 -0.149187 -0.302797 -0.188726 -0.248812  280.18      0  
39996  0.527456  0.748484 -0.308659 -0.022350  0.003130   15.33      0  
39997 -0.045303  0.516037  0.016258  0.051843  0.061811  236.19      0  
39998  0.287419  0.453268  0.378507 -0.013994  0.042698    0.76      0  

[39999 rows x 31 columns]

In [3]:
X=data.iloc[:,1:-1].values 
y=data.iloc[:,-1].values

SMOTE

In [4]:
import imblearn
from imblearn.over_sampling import SMOTE

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2,random_state=0)

In [6]:
oversample = SMOTE()
X_train, y_train = oversample.fit_resample(X_train, y_train)

In [7]:
from sklearn.preprocessing import StandardScaler 
scaler = StandardScaler()
X_train=scaler.fit_transform(X_train) 
X_test=scaler.transform(X_test)

RF

In [8]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier(n_estimators=10, criterion = 'entropy', random_state=0) 
RF.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [9]:
pred_rf=RF.predict(X_test) 
pred_rf

array([0, 0, 0, ..., 0, 0, 0])

In [10]:
from sklearn.metrics import confusion_matrix, classification_report
cm_rf=confusion_matrix(y_test,pred_rf)
cm_rf

array([[7979,    1],
       [   3,   17]])

In [11]:
print(classification_report(y_test,pred_rf))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7980
           1       0.94      0.85      0.89        20

    accuracy                           1.00      8000
   macro avg       0.97      0.92      0.95      8000
weighted avg       1.00      1.00      1.00      8000



SVC

In [12]:
from sklearn.svm import SVC
SVM_rbf = SVC(kernel="rbf",random_state=0) 
SVM_rbf.fit(X_train, y_train)

SVC(random_state=0)

In [13]:
pred_rbf=SVM_rbf.predict(X_test) 
pred_rbf

array([0, 0, 0, ..., 0, 0, 0])

In [14]:
cm_rbf=confusion_matrix(y_test,pred_rbf)
cm_rbf

array([[7953,   27],
       [   5,   15]])

In [15]:
print(classification_report(y_test,pred_rbf))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7980
           1       0.36      0.75      0.48        20

    accuracy                           1.00      8000
   macro avg       0.68      0.87      0.74      8000
weighted avg       1.00      1.00      1.00      8000



ANN

In [16]:
import tensorflow as tf

2023-04-27 18:31:22.988744: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [17]:
ANN=tf.keras.models.Sequential()

In [18]:
ANN.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [19]:
ANN.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [20]:
ANN.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [21]:
ANN.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [22]:
ANN.fit(X_train, y_train, batch_size=32, epochs=5)

Epoch 1/5
1995/1995 [==============================] - 6s 2ms/step - loss: 0.1177 - accuracy: 0.9595
Epoch 2/5
1995/1995 [==============================] - 7s 3ms/step - loss: 0.0400 - accuracy: 0.9857
Epoch 3/5
1995/1995 [==============================] - 5s 3ms/step - loss: 0.0345 - accuracy: 0.9877
Epoch 4/5
1995/1995 [==============================] - 4s 2ms/step - loss: 0.0314 - accuracy: 0.9885
Epoch 5/5
1995/1995 [==============================] - 4s 2ms/step - loss: 0.0257 - accuracy: 0.9918


In [23]:
pred_ANN=ANN.predict(X_test)
pred_ANN=(pred_ANN>0.5)

250/250 [==============================] - 1s 2ms/step


In [24]:
cm_ann=confusion_matrix(y_test,pred_ANN)
cm_ann

array([[7903,   77],
       [   1,   19]])

In [25]:
print(classification_report(y_test,pred_ANN))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00      7980
           1       0.20      0.95      0.33        20

    accuracy                           0.99      8000
   macro avg       0.60      0.97      0.66      8000
weighted avg       1.00      0.99      0.99      8000



KNN

In [26]:
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(n_neighbors=5,metric="chebyshev",p=2) 
KNN.fit(X_train, y_train)

KNeighborsClassifier(metric='chebyshev')

In [27]:
pred_knn=SVM_rbf.predict(X_test) 
pred_knn

array([0, 0, 0, ..., 0, 0, 0])

In [28]:
cm_knn=confusion_matrix(y_test,pred_knn)
cm_knn

array([[7953,   27],
       [   5,   15]])

In [29]:
print(classification_report(y_test,pred_knn))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7980
           1       0.36      0.75      0.48        20

    accuracy                           1.00      8000
   macro avg       0.68      0.87      0.74      8000
weighted avg       1.00      1.00      1.00      8000



Naive

In [30]:
from sklearn.naive_bayes import GaussianNB 
bayes = GaussianNB() 
bayes.fit(X_train, y_train)

GaussianNB()

In [31]:
pred_bayes=SVM_rbf.predict(X_test) 
pred_bayes

array([0, 0, 0, ..., 0, 0, 0])

In [32]:
cm_bayes=confusion_matrix(y_test,pred_bayes)
cm_bayes

array([[7953,   27],
       [   5,   15]])

In [33]:
print(classification_report(y_test,pred_bayes))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7980
           1       0.36      0.75      0.48        20

    accuracy                           1.00      8000
   macro avg       0.68      0.87      0.74      8000
weighted avg       1.00      1.00      1.00      8000



Logictis

In [34]:
from sklearn.linear_model import LogisticRegression 
Logistic = LogisticRegression(random_state=0) 
Logistic.fit(X_train, y_train)

/Users/jiyi/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [35]:
pred_Logistic=SVM_rbf.predict(X_test) 
pred_Logistic

array([0, 0, 0, ..., 0, 0, 0])

In [38]:
cm_Logistic=confusion_matrix(y_test,pred_Logistic)
cm_Logistic

array([[7953,   27],
       [   5,   15]])

In [37]:
print(classification_report(y_test,pred_Logistic))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7980
           1       0.36      0.75      0.48        20

    accuracy                           1.00      8000
   macro avg       0.68      0.87      0.74      8000
weighted avg       1.00      1.00      1.00      8000



array([0, 0, 0, ..., 1, 1, 1])